# Generated by Django 5.0.1 on 2024-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("TITLE", models.CharField(max_length=100)),
                ("HANDLE", models.CharField(max_length=100)),
                ("QTY", models.IntegerField()),
                ("PRICE", models.IntegerField()),
                ("IMAGE", models.TextField()),
                ("WIDTH", models.IntegerField()),
                ("LENGTH", models.IntegerField()),
            ],
        ),
    ]
